import Head from 'next/head'
import axios from "axios";
import Image from 'next/image'
import Featured from '../components/Featured'
import PizzaCard from '../components/PizzaCard'
import PizzaList from '../components/PizzaList'

import styles from '../styles/Home.module.css'

export default function Home({pizzaList}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Helensi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured/>
      <PizzaList pizzaList={pizzaList}/>
      <PizzaCard/>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      pizzaList: res.data
    },
  };
}